version: '3'
services:
  app:
    image: gcr.io/next-reddit-clone/next-reddit-clone
    build:
      context: ./
    ports:
      - "3000:3000"
    stdin_open: true
    env_file:
      - .env.production
    platform: linux/amd64   
    